inference:
  - _target_: src.metrics.ClassificationAccuracy
    metric:
      _target_: torchmetrics.classification.BinaryAccuracy
    device: ${inferencer.device}
    name: Accuracy
  - _target_: src.metrics.EqualErrorRate
    name: EER
